name: MVP Branch Workflow

on:
  push:
    branches:
      - MVP-branch1
  pull_request:
    branches:
      - MVP-branch1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Ensure compatibility with your app's React version

      # Step 3: Install dependencies in client directory
      - name: Install dependencies
        working-directory: ./client
        run: npm install

      # Step 4: Build the application
      - name: Build the application
        working-directory: ./client
        run: npm run build

      # Step 5: Run linting
      - name: Run ESLint
        working-directory: ./client
        run: npm run lint

      # Step 6: Run tests
      #- name: Run tests
        #working-directory: ./client
        #run: npm test

      # Step 7: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: .next

      # Step 8: Add Security Testing - npm audit for vulnerabilities
      - name: Run SAST with npm audit
        working-directory: ./client
        run: npm audit --production